set_property IOSTANDARD LVCMOS33 [get_ports clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[0]}]
set_property PACKAGE_PIN E3 [get_ports clk_0]
set_property PACKAGE_PIN H5 [get_ports {data_out_0[0]}]
set_property PACKAGE_PIN J5 [get_ports {data_out_0[1]}]
set_property PACKAGE_PIN T9 [get_ports {data_out_0[2]}]
set_property PACKAGE_PIN T10 [get_ports {data_out_0[3]}]
set_property PACKAGE_PIN E1 [get_ports {data_out_0[4]}]
set_property PACKAGE_PIN G4 [get_ports {data_out_0[5]}]
set_property PACKAGE_PIN H4 [get_ports {data_out_0[6]}]
set_property PACKAGE_PIN K2 [get_ports {data_out_0[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports Rx_0]
set_property PACKAGE_PIN A9 [get_ports Rx_0]

set_property IOSTANDARD LVCMOS33 [get_ports {rst_n_0[0]}]
set_property PACKAGE_PIN C2 [get_ports {rst_n_0[0]}]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_0_IBUF]
